/*
  * Aim:  Even Fibonacci numbers
  *
  * Author: Saud Kadiri
  *
  * Dated: Tuesday, November 16, 2021 and Wednesday, November 17, 2021( midnight:) )
  * Reposted on: Sunday, December 5, 2021
  *
  * Details:
  *   Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  *                                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  *   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  *
  * Approach used:
  *     In the fibonacci series: 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, ...
  *     even terms start to appear from position 3; follows that every third element happens to be an even fibonacci term! Thus any term at a position multiple of 3 is even!
  *     Thus we'll be now looking at only those terms at multiple of 3 position! So the starting two terms will be Fₙ₋₃ = 8 and Fₙ₋₆ = 2; And now reducing the expression for the
  *     heirs! 
  *     So, thus we can now from the fibonacci formula have:
  *         Fₙ = Fₙ₋₁ + Fₙ₋₂
  *            =  (Fₙ₋₂ + Fₙ₋₃)          + (Fₙ₋₃  + Fₙ₋₄)                     (Since Fₙ₋₁ = Fₙ₋₂ + Fₙ₋₃ and Fₙ₋₂ = Fₙ₋₃ + Fₙ₋₄)
  *             = ((Fₙ₋₃ + Fₙ₋₄) + Fₙ₋₃) + (Fₙ₋₃ + (Fₙ₋₅ + Fₙ₋₆))              (Since Fₙ₋₄ = Fₙ₋₅ + Fₙ₋₆)
  *             = (2Fₙ₋₃ + Fₙ₋₄)         + (Fₙ₋₃ + Fₙ₋₆ + Fₙ₋₅)
  *             = 2Fₙ₋₃ + Fₙ₋₄ + Fₙ₋₃ + Fₙ₋₆ + Fₙ₋₅
  *             = 3Fₙ₋₃ + Fₙ₋₆ + (Fₙ₋₄ + Fₙ₋₅)
  *             = 4Fₙ₋₃ + Fₙ₋₆                                                (Since Fₙ₋₃ = Fₙ₋₄ + Fₙ₋₅)
  *
  *     Thus we now have the expression for even fibaonacci terms!
  *                      Fₙ = 4Fₙ₋₃ + Fₙ₋₆          
  *             On verifying Fₙ = 4(8) + 2                                   (Since Fₙ₋₃ = 8 and Fₙ₋₆ = 2 and n = 9)
  *                              = 34                           (Indeed correct!!)
  */

// defining a recursive function to calculate sum of even fibonacci
// f3 is equivalent to Fₙ₋₃ and f6: is equivalent to Fₙ₋₆ 
// sum has a default value of 10 as a fibonacci series has at least 2 terms; which we took as 2, 8 so thier sum is 10 which is the default value. 
func even_fibonacci(f3: Int, f6: Int, _ sum: Int = 10) -> Int {
    if sum > 4_000_000 {
        return sum
    }
    let f = 4 * f3 + f6   // i.e. Fₙ = 4Fₙ₋₃ + Fₙ₋₆
    return even_fibonacci(f3: f, f6: f3, sum + f)
}


print("\(even_fibonacci(f3: 8, f6: 2))")
// 4613732
